name: importer-api

on:
  push:
    branches:
      - master
      - trunk
#    paths:
#      - importer-api/**

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Pull images
      run: |
        docker pull toska/sis-importer-api:trunk
        docker pull toska/sis-importer-mankeli:trunk
        docker pull toska/sis-importer-db-api:trunk

    - name: Build 
      run: npm run dco:ci -- build
    
    - name: Start
      run: npm run dco:ci -- up -d
    
    - name: Test
      run: docker exec -t sis-importer-api npm run test 
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0 
      with:
        repository: toska/sis-importer-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ci_testing       
